[package]
name = "influxdb"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "influxdb"
path = "src/lib.rs"
doctest = false


[dependencies]
