[package]
name = "statty_db"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "statty_api"
path = "src/lib.rs"
doctest = false

[dependencies]
diesel = { workspace = true }
